version: "3.8"

services:
  database:
    image: postgres:14.1
    container_name: database
    hostname: database
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      api:
        aliases:
            - database

  nginx:
    image: nginx:1.25.0
    container_name: nginx
    volumes:
      - ./sammys-travels.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      api:

  db_migrate:
    build: ../backend/db/.
    container_name: db_migrate
    hostname: db_migrate
    env_file:
      - .env
    restart: on-failure:4
    command: ["-path", "/migrations/", "-database",  "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable&search_path=${POSTGRES_SCHEMA}", "up"]
    networks:
      api:

  backend:
    build: ../backend/.
    container_name: backend
    hostname: backend
    env_file:
      - .env-backend
    environment:
      - DB_SSL_MODE=disable # One of "require", "verify-full", "verify-ca", and "disable"
      - SPACES_KEY=${SPACES_ACCESS_KEY_ID}
      - SPACES_SECRET=${SPACES_SECRET_ACCESS_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - db_migrate
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      api:

  frontend:
    build: ../frontend/.
    container_name: frontend
    hostname: frontend
    env_file:
      - .env-frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      api:

networks:
  api:
