version: "3.8"

services:
######################
# Local infrastructure
  database:
    image: postgres:14.1
    container_name: database
    hostname: database
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      api:
        aliases:
            - database
  
  localstack:
    container_name: s3_bucket
    image: localstack/localstack:2.1.0
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3
      - DEBUG=1
      - LS_LOG=trace
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./localstack/init/init_s3.sh:/etc/localstack/init/ready.d/init_s3.sh
      - ./localstack/images:/tmp/images
      - ./localstack/cors:/tmp/cors
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      api:
######################

  nginx:
    image: nginx:1.25.0
    container_name: nginx
    volumes:
      - ./sammys-travels.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      api:

  db_migrate:
    build: ../backend/db/.
    container_name: db_migrate
    hostname: db_migrate
    env_file:
      - .env
    restart: on-failure:4
    command: ["-path", "/migrations/", "-database",  "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable&search_path=${POSTGRES_SCHEMA}", "up"]
    networks:
      api:

  backend:
    build: ../backend/.
    container_name: backend
    hostname: backend
    env_file:
      - .env
      - .env-backend
    environment: # Only needed for local development
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DB_SSL_MODE=disable # One of "require", "verify-full", "verify-ca", and "disable"
      - FORCE_PATH_STYLE=true
    depends_on:
      - db_migrate
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      api:

  frontend:
    build: ../frontend/.
    container_name: frontend
    hostname: frontend
    env_file:
      - .env-frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      api:

networks:
  api:
